### PR TITLE
Vtmbms statistics

### PR DESCRIPTION
**Pull request by nolyn**
Adding support VTM / BMS (VVC reference software) block statistics

### CODE REVIEW

**Comment by ChristianFeldmann** [comment]
Nice @nolyn. And I guess we should merge this soon, right? I mean you guys also proposed this to JCT. I only have some comments:
 - Is it really necessary to add another playlistItem... for this? Isn't this just a different type of statistics file? Is there a big difference to the "normal" statistics files? Maybe it would be better to support this in one playlistItemStatisticsFile or have multiple handler for the different types ...
 - If we choose to have different playlistItems for this we should have a base class which includes all the code which is duplicated right now (loading in the background etc...)

**Comment by nolyn** [comment]
I refactored it a bit. playlistItemStatisticsFile is now the base class of two statistics classes, one for the CSV and one for the VTMBMS format

**Comment by nolyn** [comment]
should we merge it to deployment to? or merge development again to deployment?

**Comment by ChristianFeldmann** [comment]
I merged everything into development and also merged the changes in the deployment branch back to the development branch. If we want to deploy it, we should also merge it into deployment.

**Pull request merged**
