### PR TITLE
Default decoder

### PR DESCRIPTION
**Pull request by K-os**
Hi,
I added a feature to set a default HEVC-decoder and the option to reload files with a different decoder (bypassing the default setting).

Best regards
 Gabriel

### CODE REVIEW

**Comment by K-os** [comment]
I added two more bugfixes, but now it should be ready to merge ;-)

**Comment by K-os** [comment]
Oh, ok cool. I saw you added the feature already, so less work for me ;-)

**Comment by ChristianFeldmann** [comment]
Yes sorry that you did this work and then I re-did it. Could you test if it works as you expect it to? If it does I think we can just close this PR.

**Comment by K-os** [comment]
The default decoder setting looks good to me. There was another feature in my pull-request, that added a context menu entry for HEVC-files to reload them with a different decoder in case you don't want to use the default.
I can look into reimplementing that next week, if that feature is of general interest.

**Pull request closed without merging**
