### PR TITLE
Better detection for nv21 extension name by ignoring case

### PR DESCRIPTION
**Pull request by rogers0**

### CODE REVIEW

**Comment by rogers0** [comment]
@ChristianFeldmann ping
do you have any concern regarding to this patch?

BTW. this software is already hit debian and ubuntu:
- https://tracker.debian.org/pkg/yuview
- https://launchpad.net/ubuntu/+source/yuview

**Comment by ChristianFeldmann** [comment]
Hi. Thank you for reminding me of this again. I just did not see the PR. Sorry about that. 
Uh that looks interesting. But what does this concretely mean? I am not that deep in the debian/ubuntu packaging thigs. Did someone submit YUView for inclusion there? Can I help here somehow?

**Comment by rogers0** [comment]
@ChristianFeldmann thanks for merging this PR!

Yes, I packaged this into debian, and ubuntu automatically synced with debian.
Now version 2.6 only built well on x86 platform:
- https://buildd.debian.org/status/package.php?p=yuview

And version 2.7 seems better, but still need some time to confirm:
- https://buildd.debian.org/status/package.php?p=yuview&suite=experimental

I'll try to fix those builds on different platform. If you have time, you can also help.
The debian package's git repo is on debian's salsa, which only add "debian/" folder to the upstream (here).
- https://salsa.debian.org/multimedia-team/yuview

**Comment by ChristianFeldmann** [comment]
Nice thank you. All these packaging and build systems are new to me. 
Yes some of the issues for the 2.6 build were fixed (like the xmmint.h header issue and some of the deprecation warning which I fixed). By the way the new version 2.7 no longer depends on libqtcharts5. I did not like how that worked so I removed it again and do the plotting myself :)

**Comment by rogers0** [comment]
> Yes some of the issues for the 2.6 build were fixed (like the xmmint.h header issue and some of the deprecation warning which I fixed).

Really appreciated!
Yes, I can see so far each platform built well.
- https://buildd.debian.org/status/package.php?p=yuview&suite=experimental

> By the way the new version 2.7 no longer depends on libqtcharts5. I did not like how that worked so I removed it again and do the plotting myself :)

Understood. And I confirmed it build well after removing libqt5charts5-dev.
So now it only depends on 2 packages under Debian:
- qt5-qmake
- libqt5opengl5-dev

**Comment by ChristianFeldmann** [comment]
Yep those are the only two dependencies. 
Nice. Let me know if something fails. If it is just compiler warnings being treated as errors or other small things then I can easily fix those.

**Pull request merged**
