### PR TITLE
add generated build files to gitignore

### PR DESCRIPTION
**Pull request by slhck**
Prevent unclean Git directory after build on Linux

### CODE REVIEW

**Comment by ChristianFeldmann** [comment]
Hi. Thanks for the suggestion. But in tree builds (it looks like that is what you tried) are very much discouraged. Please create a directory somewhere (e.g. in the YUView folder. The suggested name is `build`) and execute qmake and the build in there:
```
mkdir build
cd build
qmake ..
make -j 16
```
The `build` directory is already completely covered by the gitignore and the build will put all files (.o files, moc files and binaries) into that build folder.

**Comment by slhck** [comment]
In that case it would make sense to add this to the documentation. It does not mention the steps you listed.

**Comment by ChristianFeldmann** [comment]
You are right. The [wiki page](https://github.com/IENT/YUView/wiki/Compile-YUView) does not make this clear enough. I updated the page to make it really clear to do an out of tree build.

**Comment by slhck** [comment]
Thanks, that makes much more sense!

**Pull request closed without merging**
