### PR TITLE
Add VUYA support

### PR DESCRIPTION
**Pull request by uartie**
VUYA is the packed byte order for microsoft AYUV

https://docs.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering#ayuv

### CODE REVIEW

**Comment by ChristianFeldmann** [comment]
Sometimes I have the impression that some YUV formats were just invented for the sake of using something that was not used before. 😄

**Comment by uartie** [comment]
Microsoft's "AYUV" documentation was published in 2002 according to the above link :wink:

**Comment by uartie** [comment]
FWIW: In gstreamer, AYUV and VUYA is supported as the literal byte-order.  For ffmpeg, there is a [pending] patch to add `0yuv` which follows Microsoft's definition (https://patchwork.ffmpeg.org/project/ffmpeg/patch/1575470593-7732-1-git-send-email-linjie.fu@intel.com/).

**Comment by ChristianFeldmann** [comment]
So the FOURCC code is `AYUV` where the actual order of the bytes per pixel is `VUYA`. That makes perfect sense 😆 
But thank you for you input on YUView :)

**Review by ChristianFeldmann — APPROVED** [review]

**Comment by uartie** [comment]
> So the FOURCC code is `AYUV` where the actual order of the bytes per pixel is `VUYA`. That makes perfect sense 
> But thank you for you input on YUView :)

Yes, this has confused and annoyed many people... including myself :stuck_out_tongue_closed_eyes:

**Pull request merged**
