### PR TITLE
Signal-Slot Connection Work Etc.

### PR DESCRIPTION
**Pull request by KubaO**

### CODE REVIEW

**Comment by ChristianFeldmann** [comment]
Thanks again for the work. I used the QObject::startTimer function in the playback controller because for this, we are going for maximum precision/speed. I searched the web a little bit and read an article where it was claimed that the QObject::startTimer function was the most accurate way of using Timers. This as a while ago though so I don't know if this is still true.

**Comment by KubaO** [comment]
I'll try and explain the rationale behind some of the changes.

In Qt, there is only one underlying timer mechanism implemented by the event dispatcher system. It is exposed via the low-level `QObject::startTimer`/`QObject::killTimer` API. Because it is a C-style API,  it shouldn't really be used: it doesn't manage resources for you. The `QBasicTimer` is the proper C++ class that encapsulates a timer ID and ensures that the timer doesn't leak. It is a so-called zero-cost abstraction: using it gives you resource management at no cost over a manual solution of having an `int timerId` and calling `startTimer` and `killTimer` manually.

The notion of a zero-cost abstraction is very important in C++. It is nowadays perhaps the entire goal of where C++ standardization efforts are going: resource management at no extra cost, and much less boilerplate code. That's why you use `QMutexLocker` over manual mutex lock/unlock, `QScopedPointer` or `std::unique_ptr` over manual `new`/`delete`, `QSignalBlocker` over manual disconnect-reconnect, `QFile` over `fopen`/`fclose`, `QScopedValueRollback` over setting and resetting a value as you enter/exit a scope, and so on.

The `QTimer` is another timer API that also is a `QObject` and emits a signal on timer timeout. Tthere's not much reason to use `QTimer` inside of a `QObject`: you have a `QObject` to work with already. The `QBasicTimer` is *the* timer API to use inside a `QObject`.

**Comment by ChristianFeldmann** [comment]
Aah thanks for the explanation. So using either QBasicTimer or QObject::startTimer results in the same compiled code. I just remember that in the articel it was mentioned to avoid the signal/slot mechanism of Qt for the timer. But the QBasicTimer also does not use this. Thank you!

**Comment by KubaO** [comment]
Yes, the signal/slot mechanism incurs a small overhead. If you do anything non-trivial in the slot, the overhead is not significant. I have an answer on StackOverflow with a simple signal slot test harness to measure that overhead. Signal-slot connections that carry no parameters are especially quick. They amount to locking a low-contention mutex and doing a call via a method pointer.

**Pull request merged**
