### PR TITLE
CI: don't re-upload the flatpak bundle

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
it's already done by the action if the build succeeds

### CODE REVIEW

**Comment by ChristianFeldmann** [comment]
So the `flatpak-github-actions` already does this? Nice.

**Comment by bilelmoussaoui** [comment]
> So the `flatpak-github-actions` already does this? Nice.

Yes, my idea is 0 effort working CI with minimal required configuration from the developer

**Comment by nolyn** [comment]
Great. I also tested it in my fork, it does. @bilelmoussaoui, do you have any advice on how to synchronize the release on flathub with the one generated by CI here? So far I believe I manually have to change the tag in the flathub repo (https://github.com/flathub/de.rwth_aachen.ient.YUView/) every time there is release.

**Comment by bilelmoussaoui** [comment]
> Great. I also tested it in my fork, it does. @bilelmoussaoui, do you have any advice on how to synchronize the release on flathub with the one generated by CI here? So far I believe I manually have to change the tag in the flathub repo (https://github.com/flathub/de.rwth_aachen.ient.YUView/) every time there is release.

Currently, there are no plans to offer such possibility as we lack some infrastructure work on that side. But there are plans to simplify things a bit using https://github.com/flathub/flatpak-external-data-checker/. The issue with using the build from the github action as is, is that you will end up with a x86_64 option only.

**Pull request merged**
