### PR TITLE
WIP: Building using CMake (and qt6)

### PR DESCRIPTION
**Pull request by nolyn**
I added some CMake files for building YUView. I'm able to build and run with vscode on Linux. Haven't tested other platforms.

We can consider changing to CMake in the future or use it as an alternative build system for robustness. I already found a missing "pragma once" that tripped CMake up. 
Wasn't packaging on windows relatively complicated? Maybe there are some better cmake based options, but I can't look into that.

Still have to add all the install stuff we had in the qt project files. And configure CI.

After writing the CMake files I'm wondering why we have several qt project files? I kept the structure, but I think I can write a single CMake file that will still be quite compact. Having it separate makes sense if we won't to build things separately, i.e. YUViewLib and YUViewApp. But that only works for YUViewLib, since YUViewApp depends on it.

### CODE REVIEW

**Comment by nolyn** [comment]
3bee156 is the option of having a single CMake file for the whole configuration. 
the targets can still be built independently. ie. one can choose to build only YUVLib. but has to configure everything

**Comment by nolyn** [comment]
b6d4e3b  has a complete cmake file for the lib. the rest is done by the main cmake file. i think this is the cleanest option

**Comment by ChristianFeldmann** [comment]
Hi. Nice. I was also thinking that cmake is a good idea going forward. And it also is the main build system for Qt projects. So at some point qmake will be deprecated in favor of cmake. However, this will not work with Qt5 currently. Maybe there is also a way to build the Qt5 version with cmake (as in make the CmakeFile compatible with both versions)? Then we could deprecate qmake already and only use cmake for all builds. 

I guess you included the compilation of Qt in CI for testing?

**Comment by nolyn** [comment]
I can have a look at building qt5 with cmake. I think I saw some examples somewhere. Should be possible. I managed to build with qt6 and ubuntu 20.04 so far, but the test don't work yet for some reason. Works locally, but not in the workflow. Not sure how to debug it. Are there docker images for the systems that are used in the workflows available?

**Comment by ChristianFeldmann** [comment]
Ah yes the tests ... that was another thing I did not think of. 
There are no images available I think for the CI. No idea what they run under the hood. Since Github was bought by Micosoft my wild guess is that it is something azure internal ... although it could also be a combination of everything.
Here is some info: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by nolyn** [comment]
the testing problem is related to having no display. That's why it works on my laptop. I can reproduce it if I run the tests on a virtual terminal. 
Should the tests even need a graphical display? I don't see something like that in the old build script. Maybe I linked to much stuff to the tests.

**Comment by ChristianFeldmann** [comment]
Aah I know why. That happens if you link to the GUI module. So for the tests in qmake I explicitly remove the GUI module (`QT -= gui`) for building. Then you get a command line program that will not require a GUI or any x11 modules.

**Comment by nolyn** [comment]
there is no -= gui equivalent in cmake. but after some reading i found how to do it. by default cmake pulls libraries in from dependencies (YUViewLib) of a target. it can be avoided by declaring the relevant libraries PRIVATE in the dependency. More details here: https://leimao.github.io/blog/CMake-Public-Private-Interface/

**Comment by ChristianFeldmann** [comment]
Aah very cool. I knew CMake can do it. That thing can do everything. The question was only how. 
Another option which I found yesterday is to link the tests agains GUI and launch them with `-platform offsecreen` which will not look for a GUI system but just render to an offscreen buffer (if any rendering takes place). This could be used to test some GUI things like the playlistItems. But I think it is cleaner if we have some basic tests which don't rely on GUI at all. This is also a cleaner separation in the code. At some point I was thinking about actually having separate parts of the code (like the decoders or the statistics handling or the parsers) that don't need Qt at all. That would make that code super reusable for other projects.

**Comment by nolyn** [comment]
That would have been an easier fix :). But I also think its cleaner not to link it when its not required. I was also wondering about the project structure. If you saw my first comment, I can put everything in one CMakeList.txt. Atm it is split into YUViewLib (can be build indendently with its CMakeList.txt) and the rest. Not sure anyone would want to build YUViewLib separately, but if we libraries independent from Qt that would be nice to have.

**Comment by ChristianFeldmann** [comment]
Yes maybe with CMake we can do things differently. Especially for the test cases. (Maybe we could here even switch to google-test. The qtest framework is ... well it works for now but its not really feature rich). 
The idea of the structure is:
 - **YUViewLib** contains all the actual code and builds a static library. Probably nobody will build only this. The ultimate goal is to further structure things out into modules (e.g. parsing, decoding).
 - **YUViewApp** links to the lib and opens the main window. Thats is.
 - **YUViewTest** Just tests. Links to YUViewLib. 

The advantage is that we can build many executables (testing is plenty of standalone executables) without building the YUViewLib code multiple times.

**Comment by nolyn** [comment]
alright. for that scenario i think its simplest do have a single cmake file. if the structure gets more complicated we can add more

**Comment by ChristianFeldmann** [comment]
By the way:
 - I saw that you are building Qt6 in this build. I think we should keep this separate. I already release a built version of Qt6 in https://github.com/ChristianFeldmann/YUViewQt and we should take it from there. I am also working on an update to Qt6 already (which requires a few changes). So we should merge Qt6 support with that PR and the cmake stuff in another one.

**Comment by nolyn** [comment]
I was using the cache action to stash the last build to speed it up. Good to know you already have a built.

**Comment by ChristianFeldmann** [comment]
Yep I also looked that up. The cache is also a cool idea but caches are only valid for a maximum of 7 days so not really suitable for something as heavy as building Qt.

**Comment by nolyn** [comment]
cmake file is now compatible with qt5 and qt6. builds so far for linux, except ubutnu 20.04. need a qt built for that. have to look into the other platforms as well

**Pull request closed without merging**
