### PR TITLE
Adding flatpak automatically to Releases

### PR DESCRIPTION
**Pull request by nolyn**
Should now also work with ffmpeg, it is build along the way. 

I don't see any way to automatically sync the flatpaks on flathub with the one build here, unfortunately. 

Could still move the de.rwth_aachen.ient.YUView.yaml  and the patch to another directory, if this is too much clutter

### CODE REVIEW

**Review by ChristianFeldmann — COMMENTED** [review]
Alright. I approve 😆 
The only thing I was wondering if there may be a cleaner way to not build the unit-tests. The best option would be a qmake option so that you can make something like
```
qmake -nounittest ../../
```

**Review by ChristianFeldmann — APPROVED** [review]

**Comment by nolyn** [comment]
> Alright. I approve laughing
> The only thing I was wondering if there may be a cleaner way to not build the unit-tests. The best option would be a qmake option so that you can make something like
> 
> ```
> qmake -nounittest ../../
> ```

Yes, that would be cleaner. I had a quick look, I think the syntax is something like

```
qmake  CONFIG+=UNITTESTS
```
However, should building the tests be on or off per default?

**Comment by ChristianFeldmann** [comment]
Ah cool. I really like that. I think this is a design decision that we have to make.
 - Build unit tests by default. This would mean quite some overhead for most people who don't want to build these ever.
 - Only build them in CI. 
I like the option to only build them on request. Most people will never build these. And if you want to you can just do `CONFIG+=UNITTEST`. So I am pro only building them on demand.

**Comment by nolyn** [comment]
alright. then i'll change the config to do it on demand only. guess than we also have to update all the other workflows to add the unittests  there explicitly

**Comment by nolyn** [comment]
Should work now. I added CONFIG+=UNITTESTS  to the qmake Build.yml as well. But I also didn't get any fails without so  I don't know if it works. Where can you see if the tests have been run?

**Comment by ChristianFeldmann** [comment]
When you click the green check mark you can go directly to the Github Actions where everything is built and tested. Or you can navitgate there manually. But for some reason the normal `Build.yml` does not seem to be executed anymore. That is super strange.

**Comment by ChristianFeldmann** [comment]
Ah I think I know because it is in your fork. Let me merge it into the IENT repo. Then we should see everything working.

**Pull request merged**
